Add repo settings.
mobilecoinfoundation/cookiecutters pull request #15
Opened 2023-02-17 23:55 UTC by jcape

- Add settings.yml
- Protect access to settings.yml and CODEOWNERS

### Motivation

This PR applies settings.yml to this repository, in the hope that we're able to also work it into the templates.

2023-02-17 23:55 UTC, jcape commented
Current dependencies on/for this PR:
* main
  * **PR #15** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/cookiecutters/15" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/cookiecutters/15?utm_source=stack-comment).

2023-02-18 00:24 UTC, nick-mobilecoin requested changes
Just need to fix the one label

2023-02-18 00:24 UTC, nick-mobilecoin commented on .github/settings.yml
> +    description Medium-sized PRs
:wrench: 
```suggestion
    description: Medium-sized PRs
```

2023-02-18 00:24 UTC, nick-mobilecoin commented on .github/settings.yml
> +      required_conversation_resolution: true
:question: Did we want required signatures?
```suggestion
      required_conversation_resolution: true
      required_signatures: true
```

2023-02-21 15:15 UTC, nick-mobilecoin approved these changes

2023-02-21 15:15 UTC, merged