Fix GHA link.
mobilecoinfoundation/cookiecutters pull request #37
Opened 2023-03-01 20:02 UTC by jcape

- Adjust to badges/shields#8671

### Motivation

The "build' chiclet has a big ugly link in it. This will fix that.

2023-03-01 20:03 UTC, jcape commented
Current dependencies on/for this PR:
* main
  * **PR #36** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/cookiecutters/36" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #37** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/cookiecutters/37" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/cookiecutters/37?utm_source=stack-comment).

2023-03-01 21:29 UTC, nick-mobilecoin requested changes
looks like arch went away, and also the rendered output needs to be updated

2023-03-01 21:29 UTC, nick-mobilecoin commented on rust/repo/{{ cookiecutter.repo_name }}/README.md
>  {%- endif %}
:x: I don't think the arch should have gone away

2023-03-02 00:09 UTC, nick-mobilecoin approved these changes

2023-03-02 00:09 UTC, merged